Card/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^card/', include('CardSystem.urls', namespace='card')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CardSystem/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

    url(r'^$', views.index, name='home'),                   # 主页
    url(r'^index/$', views.index, name='index'),            # 主页
    url(r'^login/$', views.login, name='login'),            # 登陆页面
    url(r'^register/$', views.register, name='register'),   # 注册页面
    url(r'^leave/$', views.leave, name='leave'),            # 退出处理
    url(r'^(?P<card_id>[\d]+)/$', views.card, name='card'),     # 名片页面
    url(r'^edit/$', views.edit, name='edit'),
    url(r'^messages/$', views.messages, name='messages'),

]

CardSystem/models.py
from django.db import models


def image_path(instance, filename):
    return './cards/%s/%s' % (instance.username, filename)


def background_path(instance, filename):
    return './background/%s/%s' % (instance.username, filename)


class Cards(models.Model):
    # 名片对应的用户, 内容对应 Users.username
    username = models.CharField(max_length=18)
    # 名片标题
    title = models.CharField(max_length=32)
    # 联系方式
    name = models.CharField(max_length=16)
    phone = models.IntegerField()
    qq = models.IntegerField()
    wechat = models.CharField(max_length=32)
    email = models.CharField(max_length=32)
    address = models.CharField(max_length=50)
    # 背景图*1 和 名片图片*10
    background = models.FileField(upload_to=background_path)
    image0 = models.FileField(upload_to=image_path)
    image1 = models.FileField(upload_to=image_path)
    image2 = models.FileField(upload_to=image_path)
    image3 = models.FileField(upload_to=image_path)
    image4 = models.FileField(upload_to=image_path)
    image5 = models.FileField(upload_to=image_path)
    image6 = models.FileField(upload_to=image_path)
    image7 = models.FileField(upload_to=image_path)
    image8 = models.FileField(upload_to=image_path)
    image9 = models.FileField(upload_to=image_path)
    time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Users(models.Model):
    username = models.CharField(max_length=18)
    password = models.CharField(max_length=18)
    create_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.username


class Messages(models.Model):
    # 留言者的信息
    name = models.CharField(max_length=16)
    phone = models.IntegerField()
    # 留言内容
    content = models.TextField(max_length=200)
    # 留言目标用户, 内容对应 Users.username
    target_user = models.CharField(max_length=18)

    def __str__(self):
        return self.target_user

CardSystem/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from CardSystem import models
from django.views.decorators.csrf import csrf_exempt
import re
# **** 一些共享变量 ****
name_regex = r'[a-zA-Z0-9]{6,18}'
pass_regex = r'[\w\W]{8,18}'
check_name = re.compile(name_regex)
check_pass = re.compile(pass_regex)
# **** 一些共享变量 ****



# 首页
# 显示欢迎信息和名片列表
def index(request):
    # 若已登录则显示欢迎信息
    if request.method == 'GET':
        isLogin = request.session.get('login_user', '')
        params = {}
        if isLogin != '':
            params['message'] = isLogin
        lists = models.Cards.objects.all()
        params['lists'] = lists
        return render(request, 'CardSystem/index.html', params)


# 登录页面 [基本OK]
@csrf_exempt
def login(request):
    if request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        # 检测username的字符组成
        check = check_name.match(username)
        if check:
            is_matched = models.Users.objects.filter(username=username, password=password)  # 查找输入是否匹配
            if is_matched:
                request.session['login_user'] = username                # 登陆成功记录session信息
                return HttpResponseRedirect('/card/index')
            else:
                return render(request, 'CardSystem/login.html', {'error2': '用户名不存在或者密码错误!'})
        else:
            return render(request, 'CardSystem/login.html', {'error1': '用户名只能由数字和字母组成!'})
    else:
        message = request.session.get('message', '')    # 若是由注册成功跳转则显示注册成功信息
        if message != '':
            del request.session['message']
            return render(request, 'CardSystem/login.html', {'message': message})
        return render(request, 'CardSystem/login.html')


# 注册页面 [基本OK]
@csrf_exempt
def register(request):
    if request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        password2 = request.POST.get('password2', '')
        # 检测用户名输入的合法性 [缺少长度和字符组成判断]
        check = check_name.match(username)                              # 用户名只能有字符和数字组成, 长度为6-18
        if check:
            is_exist = models.Users.objects.filter(username=username)   # 判断用户名是否已经存在
            if is_exist:
                return render(request, 'CardSystem/register.html', {'error1': '用户名已经存在!'})
            else:
                check2 = check_pass.match(password)                     # 密码长度为8-18
                if check2:
                    if password != password2:                           # 判断两次输入的密码是否一致
                        return render(request, 'CardSystem/register.html', {'error3': '两次密码输入不一致!'})
                    else:                                               # 输入合法, 将数据插入数据表
                        models.Users.objects.create(username=username, password=password)
                        request.session['message'] = '注册成功!'
                        return HttpResponseRedirect('/card/login')      # 注册成功, 跳转
                else:
                    return render(request, 'CardSystem/register.html', {'error2': '密码长度为8-18位!'})
        else:                                                           # 用户名出现数字和字母以外的字符
            return render(request, 'CardSystem/register.html', {'error1': '用户名只能由数字和字母组成, 长度为6-18位!'})
    else:
        return render(request, 'CardSystem/register.html')



# 用户退出
def leave(request):
    del request.session['login_user']              # 清除用户登陆状态session
    # del request.session['message']                 # 清除未读取的信息
    return HttpResponseRedirect('/card/index')     # 返回主页


# 名片页面
# [未完成] 如果是名片的所有者则显示编辑选项, 否则不可编辑
def card(request, card_id):
    check = models.Cards.objects.filter(id=card_id)
    if check:
        cards = models.Cards.objects.get(id=card_id)
        return render(request, 'CardSystem/card.html', {'card': cards})
    else:
        return render(request, '404')


#创建个人页面
@csrf_exempt
def edit(request):
    if request.method == 'GET':
        if request.session.get('login_user', "") == "":
            text = {'fail': '请先登陆！'}
            return render(request, 'CardSystem/fail.html', text)
        return render(request, 'CardSystem/edit.html')
    elif request.method == 'POST':
        username = request.session.get('login_user', "")
        title = request.POST['title']
        name = request.POST['name']
        phone = request.POST['phone']
        address = request.POST['address']
        email = request.POST['email']
        wechat = request.POST['wechat']
        qq = request.POST['qq']
        is_exist = models.Cards.objects.filter(username=username, title=title, name=name, phone=phone, address=address, email=email,
                                               wechat=wechat, qq=qq)
        text = {
            'fail': "已经存在了！",
            'success': '创建成功！',
        }
        if is_exist:
            return render(request, 'CardSystem/fail.html', text)
        else:
            models.Cards(username=username, title=title, name=name, phone=phone, address=address, email=email, wechat=wechat, qq=qq).save()
            return render(request, 'CardSystem/success.html', text)

#留言页面
@csrf_exempt
def messages(request):
    if request.method == 'GET':
        return render(request, 'CardSystem/messages.html')

CardSystem/templates/CardSystem/card.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>名片信息</title>
    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <!--<link rel="stylesheet" href="css/bootstrap.min.css">-->
    <!--微信UI-->
    <link href="https://cdn.bootcss.com/weui/1.1.1/style/weui.min.css" rel="stylesheet">

</head>
<body>
<!-- 基本信息 -->
<h1>title: {{ card.title }}</h1>
<p>name: {{ card.name }}</p>
<p>phone: {{ card.phone }}</p>
<p>qq: {{ card.qq }}</p>
<p>wechat: {{ card.wechat }}</p>
<p>email: {{ card.email }}</p>
<p>address: {{ card.address }}</p>

<!-- 展示图片 -->
<!--<p>image0: {{ card.image0 }}</p>-->
<!--<p>image1: {{ card.image1 }}</p>-->
<!--<p>image2: {{ card.image2 }}</p>-->
<!--<p>image3: {{ card.image3 }}</p>-->
<!--<p>image4: {{ card.image4 }}</p>-->
<!--<p>image5: {{ card.image5 }}</p>-->
<!--<p>image6: {{ card.image6 }}</p>-->
<!--<p>image7: {{ card.image7 }}</p>-->
<!--<p>image8: {{ card.image8 }}</p>-->
<!--<p>image9: {{ card.image9 }}</p>-->

</body>
</html>

CardSystem/templates/CardSystem/edit.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"> 
	<title>个人页面</title>
	<link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">  
	<script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
	<script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
<form role="form" method="post" action="/card/edit/">
	<div class="form-group">
		<label for="name">标题</label>
		<input type="text" class="form-control" id="title" name="title" 
			   placeholder="请输入标题">
	</div>

	<div class="form-group">
		<label for="name">姓名</label>
		<input type="text" class="form-control" id="name" name="name" 
			   placeholder="请输入你的姓名">
	</div>

	<div class="form-group">
		<label for="name">手机号码</label>
		<input type="tel" class="form-control" id="phone" name="phone" 
			   placeholder="请输入你的手机号码">
	</div>
	
	<div class="form-group">
		<label for="name">地址</label>
		<input type="text" class="form-control" id="address" name="address" 
			   placeholder="请输入地址">
	</div>

	<div class="form-group">
		<label for="name">邮箱</label>
		<input type="email" class="form-control" id="email" name="email" 
			   placeholder="请输入你的邮箱">
	</div>	

	<div class="form-group">
		<label for="name">微信</label>
		<input type="text" class="form-control" id="wechat" name="wechat" 
			   placeholder="请输入你的微信号码">
	</div>

	<div class="form-group">
		<label for="name">QQ</label>
		<input type="number" class="form-control" id="qq" name="qq"
			   placeholder="请输入你的QQ号码">
	</div>
	<input type="file" name="image" class="projectfile" value="1" >
	<button type="submit"  class="btn btn-lg btn-success btn-block">提交</button>
</form>
	</div>
</body>
</html>

CardSystem/templates/CardSystem/fail.html
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
<!--<![endif]-->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>失败</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1， user-scalable=0, maximum-scale=1.0">
    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <!--<link rel="stylesheet" href="css/bootstrap.min.css">-->
    <!--微信UI-->
    <link href="https://cdn.bootcss.com/weui/1.1.1/style/weui.min.css" rel="stylesheet">

    <!--<link rel="stylesheet" href="css/bootstrap-theme.min.css"><--></-->
    <script src="../../js/vendor/modernizr-2.8.3-respond-1.4.2.min.js"></script>
</head>

<body>

    <!--[if lt IE 8]>
                <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
<div class="weui-msg">　　　　　　　　　　　　　　　　　　　　　　
    <div class="weui-msg__icon-area"><i class="weui-icon-warn weui-icon_msg"></i></div>
    <div class="weui-msg__text-area">
        <h2 class="weui-msg__title">{{fail}}</h2>
        <p class="weui-msg__desc"></p>
    </div>
    <div class="weui-msg__opr-area">
        <p class="weui-btn-area">
            <a href="javascript:history.back();" class="weui-btn weui-btn_plain-primary">确定</a>
            <!-- <a href="javascript:history.back();" class="weui-btn weui-btn_default"></a> -->
        </p>
    </div>

</div>

  <div class="weui-footer weui-footer_fixed-bottom">
            <p class="weui-footer__links">
                <a class="weui-footer__link" href="javascript:home();">Intelligent Card System</a>
            </p>
            <p class="weui-footer__text">Copyright © 2017 S.S.H & Jerry</p>
        </div>

</body>

</html>

CardSystem/templates/CardSystem/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset='utf-8'>
 <!--微信UI-->
    <link href="https://cdn.bootcss.com/weui/1.1.1/style/weui.min.css" rel="stylesheet">

    <title>Home</title>
    <style>
        span{
            color: red;
        }
    </style>
</head>
<body>

<table>
    <tr>
        <td><a href="{% url 'card:login' %}">登录</a></td>
        <td><a href="{% url 'card:register' %}">注册</a></td>
        <td><a href="{% url 'card:leave' %}">退出登陆</a></td>
        <td><a href="{% url 'card:edit' %}"> 创建个人名片</a></td>
        <td>{{ message }}</td>
    </tr>
</table>



<div class="weui-panel__bd">
    {% for list in lists%}
                <a href="/card/{{list.id}}">
                <div class="weui-media-box weui-media-box_text">
                    <h4 class="weui-media-box__title">{{ list.title }}</h4>
                    <p class="weui-media-box__desc">{{list.name}}, {{list.phone}}, {{list.address}}, {{list.email}}
                        , {{list.wechat}}, {{list.qq}} , <span>{{list.time}}</span></p>
                </div>
                </a>

    {% endfor %}
</div>


   <div class="weui-footer weui-footer_fixed-bottom">
            <p class="weui-footer__links">
                <a class="weui-footer__link" href="javascript:home();">Intelligent Card System</a>
            </p>
            <p class="weui-footer__text">Copyright © 2017 S.S.H & Jerry</p>
        </div>
</body>
</html>

CardSystem/templates/CardSystem/login.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset='utf-8'>
 <!--微信UI-->
    <link href="https://cdn.bootcss.com/weui/1.1.1/style/weui.min.css" rel="stylesheet">
<link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">  
    <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <title>用户登陆</title>
</head>
<body>



<span style="color: green;">{{ message }}</span>
 <div class="container">
<form method="post" action="{% url 'card:login' %}" class="form-signin">
 <h2 class="form-signin-heading">用户登陆</h2>
    <br>用户名: <br>
    <input type="text" name="username" id="username" class="form-control" placeholder="请输入用户名">
    <span id="error1" style="color: red;">{{ error1 }}</span>
    <br>密码: <br>
    <input type="password" name="password" id="password" class="form-control" placeholder="请输入密码">
    <span id="error2" style="color: red;">{{ error2 }}</span>
    <div class="checkbox">
                <label ><input type="checkbox" value="remember-me">Remember me</input></label>
            </div>
    <input type="submit" value="登陆" class="btn btn-lg btn-primary btn-block">
</form>
</div>

 <div class="weui-footer weui-footer_fixed-bottom">
            <p class="weui-footer__links">
                <a class="weui-footer__link" href="javascript:home();">Intelligent Card System</a>
            </p>
            <p class="weui-footer__text">Copyright © 2017 S.S.H & Jerry</p>
        </div>
</body>
</html>

CardSystem/templates/CardSystem/messages.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>个人页面</title>
	<link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
	<script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<form role="form" method="post" action="">
	<div class="form-group">
		<label for="name">姓名</label>
		<input type="text" class="form-control" id="name" name="name"
			   placeholder="请输入你的姓名">
	</div>

	<div class="form-group">
		<label for="name">手机号码</label>
		<input type="tel" class="form-control" id="phone" name="phone"
			   placeholder="请输入你的手机号码">
	</div>

	<div class="form-group">
    <label for="name">内容</label>
    <textarea class="form-control" rows="3" name="content"></textarea>
  </div>

	<button type="submit" class="btn btn-default">提交</button>
</form>

</body>
</html>


<!-- 留言：        name
	Phone
Content -->

CardSystem/templates/CardSystem/register.html
<!DOCTYPE html>
<html lang="en">
<head>
 <!--微信UI-->
    <link href="https://cdn.bootcss.com/weui/1.1.1/style/weui.min.css" rel="stylesheet">
 <link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">  
    <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
    <title>用户注册</title>
</head>
<body>

<table>
    <tr>
        <td><a href="{% url 'card:index' %}">首页</a></td>
    </tr>
</table>
<div class="container">
<form method="post" action="{% url 'card:register' %}" class="form-signin">
    <h2 class="form-signin-heading">请注册</h2>
    <br>用户名: <br>
    <input type="text" name="username" id="username" class="form-control" placeholder="请输入用户名">
    <span id="error1" style="color: red;">{{ error1 }}</span>
    <br>密码: <br>
    <input type="password" name="password" id="password" class="form-control" placeholder="请输入密码">
    <span id="error2" style="color: red;">{{ error2 }}</span>
    <br>确认密码: <br>
    <input type="password" name="password2" id="password2" class="form-control" placeholder="请再次输入密码">
    <span id="error3" style="color: red;">{{ error3 }}</span>
    <br><br>
    <div class="checkbox">
                <label ><input type="checkbox" value="remember-me">Remember me</input></label>
            </div>
    <input type="submit" value="注册" class="btn btn-lg btn-warning btn-block">
</form>
</div>

 <div class="weui-footer weui-footer_fixed-bottom">
            <p class="weui-footer__links">
                <a class="weui-footer__link" href="javascript:home();">Intelligent Card System</a>
            </p>
            <p class="weui-footer__text">Copyright © 2017 S.S.H & Jerry</p>
        </div>
</body>
</html>

CardSystem/templates/CardSystem/success.html
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
<!--<![endif]-->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>成功</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1， user-scalable=0, maximum-scale=1.0">
    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <!--<link rel="stylesheet" href="css/bootstrap.min.css">-->
    <!--微信UI-->
    <link href="https://cdn.bootcss.com/weui/1.1.1/style/weui.min.css" rel="stylesheet">

    <!--<link rel="stylesheet" href="css/bootstrap-theme.min.css"><--></-->
    <script src="../../js/vendor/modernizr-2.8.3-respond-1.4.2.min.js"></script>
    <style type="text/css">
        span{
            color:red;
        }

    </style>
</head>

<body>

    <!--[if lt IE 8]>
                <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

<div class="weui-msg">　　　　　　　　　　　　　　　　　　　　　　
    <div class="weui-msg__icon-area"><i class="weui-icon-success weui-icon_msg"></i></div>
    <div class="weui-msg__text-area">
        <h2 class="weui-msg__title">{{success}}</h2>
        <p class="weui-msg__desc"></p>
    </div>
    <div class="weui-msg__opr-area">
        <p class="weui-btn-area">
            <a href="javascript:history.back();" class="weui-btn weui-btn_primary">确定</a>
            <!-- <a href="javascript:history.back();" class="weui-btn weui-btn_default"></a> -->
        </p>
    </div>

</div>

  <div class="weui-footer weui-footer_fixed-bottom">
            <p class="weui-footer__links">
                <a class="weui-footer__link" href="javascript:home();">Intelligent Card System</a>
            </p>
            <p class="weui-footer__text">Copyright © 2017 S.S.H & Jerry</p>
        </div>
    <!--<script src="../js/vendor/bootstrap.min.js"></script>-->

</body>

</html>

CardSystem/templates/CardSystem/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <title>Test Upload</title>
</head>
<body>

<div class="container">
    <form method="post" action="/card/test/" enctype="multipart/form-data">
        <div class="form-group">
            <label for="name">标题</label>
            <input type="text" class="form-control" id="title" name="title"
                   placeholder="请输入标题">
        </div>

        <div class="form-group">
            <label for="name">姓名</label>
            <input type="text" class="form-control" id="name" name="name"
                   placeholder="请输入你的姓名">
        </div>

        <div class="form-group">
            <label for="name">手机号码</label>
            <input type="tel" class="form-control" id="phone" name="phone"
                   placeholder="请输入你的手机号码">
        </div>

        <div class="form-group">
            <label for="name">QQ</label>
            <input type="text" class="form-control" id="qq" name="qq"
                   placeholder="请输入你的QQ号码">
        </div>

        <div class="form-group">
            <label for="name">image1</label>
            <input type="file" class="form-control" id="image0" name="image0">
        </div>

        <button type="submit" class="btn btn-default">提交</button>
    </form>
</div>

</body>
</html>